// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebCatalogOfFootballers.Data;

#nullable disable

namespace WebCatalogOfFootballers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241213185925_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebCatalogOfFootballers.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Россия"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "США"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Италия"
                        });
                });

            modelBuilder.Entity("WebCatalogOfFootballers.Models.Footballer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Birthday")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamNameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GenderId");

                    b.HasIndex("TeamNameId");

                    b.ToTable("Footballers");
                });

            modelBuilder.Entity("WebCatalogOfFootballers.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GenderName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenderName = "Мужчина"
                        },
                        new
                        {
                            Id = 2,
                            GenderName = "Женщина"
                        });
                });

            modelBuilder.Entity("WebCatalogOfFootballers.Models.TeamName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameTeam")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TeamNames");
                });

            modelBuilder.Entity("WebCatalogOfFootballers.Models.Footballer", b =>
                {
                    b.HasOne("WebCatalogOfFootballers.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("WebCatalogOfFootballers.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("WebCatalogOfFootballers.Models.TeamName", "TeamName")
                        .WithMany()
                        .HasForeignKey("TeamNameId");

                    b.Navigation("Country");

                    b.Navigation("Gender");

                    b.Navigation("TeamName");
                });
#pragma warning restore 612, 618
        }
    }
}
